// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD_tAcM5OA65OT_9BoqkKvAB_ZW8Vjg9g',
    appId: '1:336171900343:web:78e4c8b684cc30c9c4dc32',
    messagingSenderId: '336171900343',
    projectId: 'mynt-hospitality',
    authDomain: 'mynt-hospitality.firebaseapp.com',
    storageBucket: 'mynt-hospitality.firebasestorage.app',
    measurementId: 'G-3VZZ46S62K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFCtfeKmNnnd_R34vS-OxWQzk3wLIuMDc',
    appId: '1:336171900343:android:4d617692d1e7f6abc4dc32',
    messagingSenderId: '336171900343',
    projectId: 'mynt-hospitality',
    storageBucket: 'mynt-hospitality.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCOUw9gys9OVv0S54zs_fiwqqfhpEwEFo',
    appId: '1:336171900343:ios:cdc3dec005d553ddc4dc32',
    messagingSenderId: '336171900343',
    projectId: 'mynt-hospitality',
    storageBucket: 'mynt-hospitality.firebasestorage.app',
    iosBundleId: 'com.example.mynt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCOUw9gys9OVv0S54zs_fiwqqfhpEwEFo',
    appId: '1:336171900343:ios:cdc3dec005d553ddc4dc32',
    messagingSenderId: '336171900343',
    projectId: 'mynt-hospitality',
    storageBucket: 'mynt-hospitality.firebasestorage.app',
    iosBundleId: 'com.example.mynt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD_tAcM5OA65OT_9BoqkKvAB_ZW8Vjg9g',
    appId: '1:336171900343:web:57b6119920b66617c4dc32',
    messagingSenderId: '336171900343',
    projectId: 'mynt-hospitality',
    authDomain: 'mynt-hospitality.firebaseapp.com',
    storageBucket: 'mynt-hospitality.firebasestorage.app',
    measurementId: 'G-1RPMY6JTPH',
  );
}
